Article.create!(
  [
    {
      title: 'Programming Language Ruby',
      body: 'Ruby is a programming language for the web and beyond. It is simple, powerful, and has a large and supportive community. It is also the primary language used to build the Ruby on Rails web framework. If you want to get started with Ruby, you\'ve come to the right place. This guide will get you up and running with Ruby in no time. Ruby is an interpreted, high-level, general-purpose programming language. It was designed and developed in the mid-1990s by yukihiro matsumoto in japan. According to its creator, ruby was influenced by perl, smalltalk, eiffel, ada, and lisp. it supports multiple programming paradigms, including functional, object-oriented, and imperative. it also has a dynamic type system and automatic memory management. Ruby\'s syntax is intended to be natural and easy to read. It is intended to help programmers write clear and maintainable code. Ruby is a dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write. Ruby is a general-purpose programming language.'
    },
    {
      title: 'Ruby on Rails',
      body: 'Ruby on Rails is a web application development framework written in Ruby under the mit license. Rails is a model–view–controller framework, providing default structures for a database, a web service, and web pages. It encourages and facilitates the use of web standards such as JSON or XML for data transfer, and HTML, CSS and JavaScript for display and user interfacing. In addition to MVC, Rails emphasizes the use of other well-known software engineering patterns and paradigms, including convention over configuration (CoC), don\'t repeat yourself (DRY), and the active record pattern.'
    },
    {
      title: 'Javascript',
      body: 'Javascript, often abbreviated as js, is a programming language that conforms to the ecma-262 specification. Javascript is high-level, often just-in-time compiled, and multi-paradigm. it has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions. Alongside html and css, javascript is one of the three core technologies of the world wide web. Javascript enables interactive web pages and is an essential part of web applications. The vast majority of websites use it, and all major web browsers have a dedicated javascript engine to execute it.'
    },
    {
      title: 'React',
      body: 'React is a free and open-source front-end Javascript library for building user interfaces or ui components. It is maintained by facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications. However, React is only concerned with rendering data to the dom, and so creating React applications usually requires the use of additional libraries for state management and routing. Redux and react-router are respective examples of such libraries. React is used to handle the view layer for web and mobile apps. React also allows us to create reusable ui components. React was first created by Jordan Walke, a software engineer working for facebook. React first deployed on facebook\'s newsfeed in 2011 and on instagram.com in 2012. It was open-sourced at jsconf us in may 2013. React Native, which enables native react development on ios and android, was announced at facebook\'s react.js conf in february 2015 and open-sourced at jsconf us in may 2015.'
    },
    {
      title: 'Redux',
      body: 'Redux is an open-source javascript library for managing application state. It is most commonly used with libraries such as react or angular for building user interfaces. Similar to facebook\'s flux architecture, it was created by dan abramov and andrew clark. Redux is a predictable state container for javascript apps. It helps you write applications that behave consistently, run in different environments (client, server, and native), and are easy to test. On the web, redux is mostly used with react with the react-redux binding. Redux can also be used as a data store for vanilla javascript apps. It is tiny (2kB, including dependencies). It is not opinionated about how your code should be structured, but rather provides a way to manage the state of your application in a predictable way. It is possible to have a single store in a web application, or to split your data handling logic into multiple stores, and compose them as needed.'
    },
    {
      title: 'Node.js',
      body: 'Node.js is an open-source, cross-platform, javascript runtime environment that executes javascript code outside of a browser. Node.js lets developers use javascript to write command line tools and for server-side scripting—running scripts server-side to produce dynamic web page content before the page is sent to the user\'s web browser. Node.js is an event-based, non-blocking, asynchronous I/O runtime that uses google\'s v8 javascript engine and libuv library. Node.js\' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. Node.js is a javascript runtime built on chrome\'s v8 javascript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js\' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. Node.js is a javascript runtime built on chrome\'s v8 javascript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient.'
    },
    {
      title: 'Express',
      body: 'Express is a minimal and flexible node.js web application framework that provides a robust set of features for web and mobile applications. With a myriad of http utility methods and middleware at your disposal, creating a robust api is quick and easy. Express provides a thin layer of fundamental web application features, without obscuring node.js features that you know and love. With a myriad of http utility methods and middleware at your disposal, creating a robust api is quick and easy. Express provides a thin layer of fundamental web application features, without obscuring node.js features that you know and love. Express is the de facto standard server framework for node.js. It is named after the express web framework, which is inspired by sinatra. It is the de facto standard server framework for node.js. It is named after the express web framework, which is inspired by sinatra. It is the de facto standard server framework for node.js. It is named after the express web framework, which is inspired by sinatra.'
    },
    {
      title: 'MongoDB',
      body: 'MongoDB is a cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License. MongoDB is written in c++. MongoDB is a cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License. MongoDB is written in c++. MongoDB is a cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License. MongoDB is written in c++. MongoDB is a cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License. MongoDB is written in c++.'
    },
    {
      title: 'PostgreSQL',
      body: 'Postgresql, often simply postgres, is an object-relational database management system (ordbms) with an emphasis on extensibility and standards compliance. As a database server, its primary function is to store data securely, supporting best practices to ensure the reliability, availability, and integrity of data. It can handle workloads ranging from small single-machine applications to large Internet-facing applications with many concurrent users. It is fully ACID compliant, has full support for foreign keys, joins, views, triggers, and stored procedures (in multiple languages). It includes most SQL:2008 data types, including INTEGER, NUMERIC, BOOLEAN, CHAR, VARCHAR, DATE, INTERVAL, and TIMESTAMP. It also supports storage of binary large objects, including pictures, sounds, or video. It has native programming interfaces for C/C++, Java, .net, Perl, Python, Ruby, Tcl, ODBC, among others, and exceptional documentation.'
    },
    {
      title: 'Programming Language C#',
      body: 'C# is a general-purpose, multi-paradigm programming language encompassing strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented (class-based), and component-oriented programming disciplines. It was developed around 2000 by microsoft within its .net initiative and later approved as a standard by ecma (ecma-334) and iso (iso/iec 23270:2006). It was designed to be a simple, modern, general-purpose, object-oriented programming language. Its development team is led by andrew wyss within microsoft. C# is intended to be a simple, modern, general-purpose, object-oriented programming language. Its development team is led by andrew wyss within microsoft. C# is intended to be a simple, modern, general-purpose, object-oriented programming language. Its development team is led by andrew wyss within microsoft. C# is intended to be a simple, modern, general-purpose, object-oriented programming language. Its development team is led by andrew wyss within microsoft.'
    },
    {
      title: 'Programming Language C',
      body: 'C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, with a static type system. By design, c provides constructs that map efficiently to typical machine instructions. It has found lasting use in applications previously coded in assembly language. Such applications include operating systems and various application software for computers ranging from supercomputers to embedded systems. C was originally developed at bell laboratories in the early 1970s by dennis ritchie for the unix operating system. C has been standardized by the american national standards institute (ansi) since 1989 (ansi c) and by the international organization for standardization (iso) since 1990 (iso c). C has been widely used for many years in applications that had formerly been coded in assembly language, including operating systems, as well as various application software for computers ranging from supercomputers to embedded systems.'
    },
  ])